// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../events.dart';
import '../rx_handlers.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BleClient>>
abstract class BleClient implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<BleClient> newInstance() =>
      RustLib.instance.api.crateApiClientsClientBleBleClientNew();

  Future<void> sendHidEvent({required List<int> event});

  Future<void> setupClientListener({required PositionVecU8Receiver receiver});

  Stream<ClientEvent> watchDevices();
}
