// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AdbClient {
  const AdbClient();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AdbClient> newInstance() =>
      RustLib.instance.api.crateApiClientsClientAdbAdbClientNew();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdbClient && runtimeType == other.runtimeType;
}
