[package]
name = "rust_lib_uni_control_hub"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.6.0"
uni_control_hub_rust = { path = "../../" }
