display_name: UniControlHub
package_name: uni-control-hub

maintainer:
  name: Rohit Sangwan
  email: rohtisangwan647@gmail.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: assets/icon/icon_rounded_corner.png

keywords:
  - UniControlHub
  - KVM
  - Synergy
  - Application

generic_name: KVM Application

categories:
  - KVM
  - Media

startup_notify: true