name: Release App
on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Apply Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - name: Install dependencies
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-0 libgtk-3-dev libblkid1 liblzma5
      - name: Enable Linux
        run: flutter config --enable-linux-desktop
      - name: Get Dependencies
        run: flutter pub get
      - name: Generate App Version
        id: app_version
        run: echo "value=$(yq '.version' pubspec.yaml)" >> $env:GITHUB_OUTPUT
      - name: Activate Packaging Tool
        run: dart pub global activate flutter_distributor
      - name: Release App
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: flutter_distributor release --name publish --jobs linux