name: Release App
on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Get version
        id: app_version
        uses: mikefarah/yq@master
        with:
          cmd: yq -r '.version' 'pubspec.yaml'
      - name: Print AppVersion
        run: echo "AppVersion=${{ steps.app_version.outputs.result }}"

# jobs:
#   linux:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Git Checkout
#         uses: actions/checkout@v3
#       - name: Apply Flutter Environment
#         uses: subosito/flutter-action@v2
#         with:
#           channel: "stable"
#           architecture: x64
#       - name: Install dependencies
#         run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-0 libgtk-3-dev libblkid1 liblzma5
#       - name: Enable Linux
#         run: flutter config --enable-linux-desktop
#       - name: Activate Packaging Tool
#         run: dart pub global activate flutter_distributor
#       - name: Build App
#         run: flutter_distributor release --name bundle --jobs linux
#       - name: Generate App Version
#         id: app_version
#         run: echo "value=$(yq '.version' pubspec.yaml)" >> $env:GITHUB_OUTPUT
#       - name: Github Release
#         uses: softprops/action-gh-release@v1
#         with:
#           tag_name: ${{ steps.app_version.outputs.value }}
#           files: |
#             dist/*/*